plugins { id 'com.android.application' }
android {
    namespace 'tw.dimserene.lrcstudio'
    compileSdk 35
    defaultConfig {
        applicationId 'tw.dimserene.lrcstudio'
        minSdk 28
        targetSdk 35
        versionCode 7
        versionName '0.1.6'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
